# This code was generated by ChatGPT in December 2024.

##############
############## Clear workspace
##############

rm(list=list(ls()))
set.seed(1988)
library(ggplot2)

##############
############## Generate fake data
##############

n <- 100
Group <- rep(c("A", "B"), each = n)
W_pre <- c(rnorm(n, mean = 70, sd = 10), rnorm(n, mean = 70, sd = 10))
W_post <- c(W_pre[1:n] + rnorm(n, mean = 5, sd = 3),
            0.5 * W_pre[(n + 1):(2 * n)] + rnorm(n, mean = 40, sd = 3))
data <- data.frame(Group, W_pre, W_post)

##############
############## Compute mean change
##############

mean_change <- aggregate(W_post - W_pre ~ Group, data = data, mean)

##############
############## Regression analysis
##############

model <- lm(W_post ~ W_pre + Group, data = data)

##############
############## Visualization
##############

ggplot(data, 
        aes(x = W_pre, 
            y = W_post, 
           color = Group)) +
geom_point() +
geom_smooth(method = "lm", se = FALSE) +
labs(title = "Visualization of Lord's Paradox",
     x = "Pre-intervention Weight",
     y = "Post-intervention Weight")